"""Artifact drafter — generates DRAFT test artifacts the founder reviews and edits.

Draft-only: returns content; the orchestrator owns the writes (single-writer).
Nothing here is ever sent or published — publish/send stays human-gated.
"""
from __future__ import annotations

from dataclasses import dataclass

SYSTEM_PROMPT = """\
You are venture-pilot's artifact drafter. Given the founder's idea and cited research, \
produce three DRAFT artifacts the founder will review and edit. Nothing is sent or \
published. Use The Mom Test discipline: ask about past behavior and money already spent, \
never pitch.

Return STRICT JSON only:
{"interview_script":"<markdown Mom-Test interview script>",
 "outreach":"<markdown with ~12 short personalized outreach drafts for the communities found>",
 "landing_html":"<a focused single-page landing page HTML with an email-capture CTA, labeled DRAFT>"}"""


@dataclass
class Artifact:
    name: str        # display name
    relpath: str     # path under the run's out/ dir
    content: str
    tag: str         # display tag


def _interview_script(idea: str) -> str:
    return f"""# Customer interview script (DRAFT) — The Mom Test

**Idea under test:** {idea}

> Rules: talk about THEIR life, not your idea. Ask about the past, not the future.
> Dig into specifics and money already spent. Do not pitch. Do not seek compliments.

## 1. Warm-up
- What's your role, and how big is your team?
- Walk me through the last time this area of your work got painful.

## 2. Past behavior (the truth lives here)
- Last time that happened, what did you actually do about it?
- What tools or workarounds are you using for it today?
- How often does this come up — daily, weekly?

## 3. Money & effort already spent
- Have you paid for anything to deal with this? What, and how much?
- Who on the team feels this most? Who owns the budget for it?

## 4. Severity
- On your worst week, what does this cost you (time, money, dropped commitments)?
- If it magically disappeared tomorrow, what would change?

## 5. Wrap (commitment, not compliments)
- Who else should I talk to about this?
- Would it be useful if I followed up when I have something to show? (gauge real interest)

_Never ask "would you use this?" — ask what they did last week._
"""


def _outreach(idea: str) -> str:
    return f"""# Outreach drafts (DRAFT — you send, after editing) — {idea}

> 12 short drafts across the communities found in research. Personalize the [brackets]
> before sending. Always disclose you're the founder; give value first; no spam.

1. **r/engineeringmanagement comment** — "Curious how other EMs handle [the pain]? I keep seeing it eat my week and want to learn how you've solved it."
2. **r/engineeringmanagement DM** — "Saw your comment on [thread]. Mind if I ask 3 questions about how your team handles [pain]? Founder researching it, not selling."
3. **Rands Leadership Slack #tools** — "What are folks using for [pain] today? Trying to map the real workflow, happy to share what I learn back."
4. **Rands Slack DM** — "Hey [name], loved your take on [topic]. Could I borrow 15 min to hear how you handle [pain]?"
5. **LinkedIn (warm)** — "[name], you've led eng at [company] through scale — how did you handle [pain] as the team grew?"
6. **LinkedIn (cold)** — "Researching how EMs at 50-200-person SaaS handle [pain]. 15 min to share your experience? Not a pitch."
7. **Email (intro via mutual)** — "[mutual] suggested I reach out — I'm mapping how teams handle [pain] and they said you've lived it."
8. **Email (cold, value-first)** — "Wrote up what 8 EMs told me about [pain]; thought you'd find it useful. Would love your read on it."
9. **X/Twitter DM** — "Your thread on [topic] nailed it. Researching [pain] — could I ask what you actually use today?"
10. **Indie Hackers post reply** — "How are you handling [pain]? Trying to understand the real workaround stack before building anything."
11. **Founder Discord** — "Quick one for EMs here: what's your current process for [pain]? Trading notes, not selling."
12. **Follow-up (after a yes)** — "Thanks again — here's a 1-pager on what I'm exploring. No pressure, just want your honest read."
"""


def _landing_html(idea: str) -> str:
    return f"""<!doctype html>
<!-- DRAFT landing page generated by venture-pilot. PUBLISH-GATED: do not deploy until you approve. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{idea} — early access</title>
<style>
  :root {{ --ink:#0A0E14; --teal:#20E3A2; --fg:#E6EDF3; --muted:#7E8CA3; }}
  * {{ box-sizing:border-box; margin:0; }}
  body {{ background:var(--ink); color:var(--fg); font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif; line-height:1.6; }}
  .draft {{ position:fixed; top:14px; right:-38px; transform:rotate(45deg); background:var(--teal); color:var(--ink); font-weight:700; padding:6px 48px; font-size:13px; }}
  main {{ max-width:680px; margin:0 auto; padding:96px 24px; }}
  h1 {{ font-size:42px; line-height:1.15; letter-spacing:-.02em; }}
  h1 b {{ color:var(--teal); }}
  p.sub {{ color:var(--muted); font-size:20px; margin-top:18px; }}
  form {{ display:flex; gap:10px; margin-top:32px; flex-wrap:wrap; }}
  input {{ flex:1; min-width:220px; padding:14px 16px; border-radius:10px; border:1px solid #243042; background:#0E1420; color:var(--fg); font-size:16px; }}
  button {{ padding:14px 22px; border:0; border-radius:10px; background:var(--teal); color:var(--ink); font-weight:700; font-size:16px; cursor:pointer; }}
  ul {{ color:var(--muted); margin-top:40px; padding-left:18px; }}
  small {{ color:var(--muted); }}
</style>
</head>
<body>
<div class="draft">DRAFT</div>
<main>
  <h1>Stop letting it <b>slip through the cracks</b>.</h1>
  <p class="sub">{idea} — for teams who are tired of the workaround.</p>
  <!-- DRAFT placeholder form — wire it to your email tool before publishing. -->
  <form onsubmit="return false">
    <input type="email" placeholder="you@company.com" aria-label="email">
    <button>Get early access</button>
  </form>
  <ul>
    <li>Built for engineering managers at growing SaaS teams</li>
    <li>Replaces the spreadsheet-and-memory workaround</li>
    <li>We'll only email you when there's something real to show</li>
  </ul>
  <p style="margin-top:48px"><small>A venture-pilot test artifact — validate demand before you build.</small></p>
</main>
</body>
</html>
"""


def template_artifacts(idea: str) -> list[Artifact]:
    return [
        Artifact("interview script", "interview-script.md", _interview_script(idea), "Mom-Test"),
        Artifact("outreach DMs", "outreach.md", _outreach(idea), "12 drafts"),
        Artifact("landing page", "landing/index.html", _landing_html(idea), "publish-gated"),
    ]


def draft(llm, idea: str, findings) -> list[Artifact]:
    """Return draft Artifacts. The orchestrator writes them; this never touches disk."""
    research_summary = "\n".join(f"- {f.label}" for f in findings if f.supported)
    user = f"Idea: {idea}\n\nCited research:\n{research_summary}\n\nDraft the three artifacts."
    try:
        data = llm.complete_json(SYSTEM_PROMPT, user, max_tokens=4000, label="draft-artifacts")
    except Exception:  # malformed model output -> never crash, fall back to a starter template
        data = {}
    if not data:
        return template_artifacts(idea)
    return [
        Artifact("interview script", "interview-script.md",
                 data.get("interview_script", _interview_script(idea)), "Mom-Test"),
        Artifact("outreach DMs", "outreach.md",
                 data.get("outreach", _outreach(idea)), "12 drafts"),
        Artifact("landing page", "landing/index.html",
                 data.get("landing_html", _landing_html(idea)), "publish-gated"),
    ]
